Bump org.springframework.boot from 2.7.18 to 3.2.2 in /service (#100)
* Bump org.springframework.boot from 2.7.18 to 3.2.2 in /service

Bumps [org.springframework.boot](https://github.com/spring-projects/spring-boot) from 2.7.18 to 3.2.2.
- [Release notes](https://github.com/spring-projects/spring-boot/releases)
- [Commits](https://github.com/spring-projects/spring-boot/compare/v2.7.18...v3.2.2)

---
updated-dependencies:
- dependency-name: org.springframework.boot
  dependency-type: direct:production
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

* Replace javax namespace with jakarta

* Spring Framework 6 replaces HttpStatus with HttpStatusCode

* Spring Boot 3 moves LocalServerPort into test namespace

* Update Spring Cloud dependency version to latest

Matching the updated version of Spring Boot, to ensure compatibility.

* Bump com.github.tomakehurst:wiremock from 2.27.2 to 3.0.1 in /service

Bumps [com.github.tomakehurst:wiremock](https://github.com/wiremock/wiremock) from 2.27.2 to 3.0.1.
- [Release notes](https://github.com/wiremock/wiremock/releases)
- [Commits](https://github.com/wiremock/wiremock/compare/2.27.2...3.0.1)

---
updated-dependencies:
- dependency-name: com.github.tomakehurst:wiremock
  dependency-type: direct:production
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

* Switch to standalone wiremock

This appears to be a common fix to the error we're seeing:
> java.lang.NoClassDefFoundError: jakarta/servlet/DispatcherType

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Adrian Clay <adrian@madetech.com>