Switch to standalone wiremock
This appears to be a common fix to the error we're seeing:
> java.lang.NoClassDefFoundError: jakarta/servlet/DispatcherType